server:
  port: 8086
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
      oauth2:
          resourceserver:
              jwt:
                  issuer-uri:  http://localhost:8180/realms/SpringBootDemoKeyCloak
                  jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
    auth:
        converter:
              resource-id: springboot-keycloak-demo-client
              principle-attribute: preferred_username

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swaggerui
